# 首页设置
index:
  # 首页大图中间的文字
  slogan:
    enable: true
    # 这里填你想写的文字
    text: "欢迎来到 aitest 技术博客"
# 文章页底部的版权声明
post:
  copyright:
    enable: true
    # 许可协议，可选项：CC_BY / CC_BY_SA / CC_BY_ND / CC_BY_NC / CC_BY_NC_SA / CC_BY_NC_ND
    license: 'CC_BY_SA'
    # 许可协议的显示文本，如果不填则会自动根据 license 生成
    license_content: '本博客所有文章除特别声明外，均采用 (CC BY-SA 4.0) 许可协议。转载请注明出处！'